### ISSUE TITLE
Android scheme colors

### ISSUE THREAD

**Issue by InioX** [Aiving/material-colors#2]
Hi, thanks a lot for writing this library!

I know this is based on the Swift version, but is there any way you could implement the Android scheme just like in typescript?

You can look at the typescript version of [scheme_android](https://github.com/material-foundation/material-color-utilities/blob/main/typescript/scheme/scheme_android.ts) for reference. I also converted this to a rust version [here](https://docs.rs/ini-material-color-utilities-rs/0.5.0/src/ini_material_color_utilities_rs/scheme/scheme_android.rs.html#9-35) a while ago (just ignore the `amoled`/`pure_dark` function)

I would make a PR but I have no idea how the dynamic scheme would work with this.

**Comment by Aiving** [comment]
Hi! After studying the provided code and searching through the official repository of material-color-utilities, it seems to me that AndroidScheme is outdated, since there is [this comment](https://github.com/material-foundation/material-color-utilities/blob/main/typescript/scheme/scheme_tonal_spot.ts#L29) and, by itself, AndroidScheme exists exclusively in the typescript version (the partial outdatedness of which is often noticed).
I don't mind adding a new scheme, as it's not difficult (CorePalette still exists). I'm just really wondering if AndroidScheme is something you would like to use.

**Comment by InioX** [comment]
Thanks for the quick response! I've been wondering why i didnt see the `AndroidScheme` implemented in any other languages.

I guess it would be better not to add it since it's outdated, I'll just remove the colors on my end and switch to your library. Thanks again! :)
